# Generated by Django 5.1.1 on 2025-06-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0002_recharge"),
    ]

    operations = []
