# Generated by Django 5.1.1 on 2025-06-02 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0003_auto_20250602_1150"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="accepted_by",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="service",
        ),
        migrations.AddField(
            model_name="order",
            name="earnings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="service_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="time",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="service_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
