# Generated by Django 5.1.1 on 2025-06-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "servicesapp",
            "0004_remove_order_accepted_by_remove_order_customer_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rechargetransaction",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
