# Generated by Django 5.1.1 on 2025-06-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0005_rechargetransaction_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="recharge",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
