# Generated by Django 5.1.1 on 2025-06-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0007_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
