# Generated by Django 5.1.1 on 2025-06-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0008_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recharge",
            name="user",
        ),
        migrations.AddField(
            model_name="notification",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="servicesapp.order",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
