# Generated by Django 5.1.1 on 2025-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0009_remove_recharge_user_notification_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="phone_number",
            field=models.CharField(default="unknown", max_length=15),
            preserve_default=False,
        ),
    ]
