# Generated by Django 5.1.1 on 2025-06-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0010_notification_phone_number"),
    ]

    operations = []
