# Generated by Django 5.1.1 on 2025-06-02 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicesapp", "0011_auto_20250602_2014"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="earnings",
        ),
        migrations.RemoveField(
            model_name="order",
            name="location",
        ),
        migrations.RemoveField(
            model_name="order",
            name="service_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="time",
        ),
        migrations.AddField(
            model_name="order",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(default="unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.CharField(default="unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="service_provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="servicesapp.serviceprovider",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
